services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      - DEVICE=auto  # Auto-detect GPU/CPU for local models
      - ENABLE_MODEL_QUANTIZATION=true  # Enable 8-bit GPU quantization or FP16 CPU optimization
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
